### ISSUE TITLE
What actually creates the 2D viewer?

### ISSUE THREAD

**Issue by SelaOAL** [Autodesk-Forge/viewer-navigation.sample#1]
Where does the distinction between the the 3D and 2D viewers happen?
The following two declarations do practically the same:

https://github.com/Autodesk-Forge/viewer-navigation.sample/blob/master/www/scripts/model.js#L42
```
     var viewer3DContainer = document.getElementById("viewer3D");
      viewer3D = new Autodesk.Viewing.Private.GuiViewer3D(viewer3DContainer);

      var viewer2DContainer = document.getElementById("viewer2D");
      viewer2D = new Autodesk.Viewing.Private.GuiViewer3D(viewer2DContainer);
```

I see that the function `loadDocument`  https://github.com/Autodesk-Forge/viewer-navigation.sample/blob/master/www/scripts/model.js#L78 don't do anything since nothing special happens after I remove its call. (it also has a syntax error [viewer2D.](https://github.com/Autodesk-Forge/viewer-navigation.sample/blob/master/www/scripts/model.js#L91))

So where is it actually created? 

I ask this because I want to add the 2D viewer into the [offline viewer](https://github.com/Developer-Autodesk/viewer-javascript-offline.sample).

**Comment by augustogoncalves** [comment]
Actually the piece of code you mentioned define the 2 views (2D and 3D), then the models are loaded on them at this line (https://github.com/Autodesk-Forge/viewer-navigation.sample/blob/master/www/scripts/model.js#L100). For questions, you can also post to forge.help@autodesk.com on using Stackoverflow.
