### ISSUE TITLE
Metadata and viewModels variables

### ISSUE THREAD

**Issue by SelaOAL** [Autodesk-Forge/viewer-navigation.sample#2]
What are the metadata and viewModels variables that are used in marker.js and model.js?

What is the data in rac.json and where can I find this data for every model?
Is it possible to generate an object for viewModels offline so it will work like what `getModels()` does?

**Comment by augustogoncalves** [comment]
the variables and contents are defined on the rac.json file and are hardcoded for those models (not something that can be defined for every model).

**Comment by SelaOAL** [comment]
Isn't this data needed for the model.js to work?

Surely by knowing how rac.json was made and what its properties represent it will be possible to write a script to generate it no?
